### ISSUE TITLE
Questions! Since I don't know where else to ask this.

### ISSUE THREAD

**Issue by itstoast27** [Adanos020/nsmwe#1]
Hey, stumbled upon this, seeing as it's fairly new, and wanted to ask some questions! So, uh: 

1. What operating systems will you be building for?
2. What all are you planning for this?
3. On how big of a scale will this be?
4. What all is currently implemented?

I use Linux, and was frustrated at the lack of a native alternative to Lunar Magic, and my search led me here, looking around for anything remotely close to it. Anyways, thanks in advance!

**Comment by Adanos020** [comment]
Hi, I didn't expect anyone to find this so fast and I'm happy to answer these questions for you. 😄

1. Initially I'm planning to build it for Windows and Linux, later also for macOS when I gain access to an Mac (or when some kind person does this for me).
2. The plans for this project are rather large I should say.
3. Here are the main features I want to include: 
- Level, Overworld, and Background editor
- Graphics editor
- Block editor
- Sprite editor
- ASM code editor with support for ASM patches
- Music composer with sample editing
- Support for plugins written in Lua
4. So far I haven't implemented much. I'm developing this project alone, after work, so it won't achieve the goals I've set too soon. Currently the program is able to parse the internal ROM header, convert between SNES and PC addresses, and display that in a basic GUI. At the moment I'm working on parsing and displaying colour palettes and graphics.

There are many reasons why I decided to kick this project off, but the main one is that FuSoYa refused to make a port of Lunar Magic for systems other than Windows or to make it open-source. I find it frustrating that nobody else decided to do it for over 20 years but here we go.

I hope NSMWE (or whatever I'm going to call it) will gain some interest from the SMW community and attract other developers willing to help making it. I welcome all contributions!
